[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AnonymousModeEnabled=true
Session\DefaultSavePath=/x-media/torrents
Session\DisableAutoTMMByDefault=true
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\ExcludedFileNames=
Session\GlobalMaxInactiveSeedingMinutes=120
Session\GlobalMaxSeedingMinutes=30
Session\IgnoreLimitsOnLAN=true
Session\IgnoreSlowTorrentsForQueueing=true
Session\MaxActiveDownloads=25
Session\MaxActiveTorrents=30
Session\MaxActiveUploads=5
Session\MultiConnectionsPerIp=true
Session\Port=31091
Session\QueueingSystemEnabled=true
Session\TempPath=/x-media/torrents/incomplete
Session\TempPathEnabled=true
Session\UseAlternativeGlobalSpeedLimit=false
Session\ValidateHTTPSTrackerCertificate=false
Session\uTPRateLimited=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
MailNotification\req_auth=true
WebUI\Address=*
WebUI\Password_PBKDF2="@ByteArray(gAiiA2/9XrIlf+3LR3cKAA==:ijzwOFvW6MRJ1M0nE4vOnyqK1NnX16/JGBMl7Vu7HnOmQhuNuHiCl8bwTeyLNwG2Q4P6RLw8Ijsib4u6ViQ3+w==)"
WebUI\Port=8090
WebUI\ServerDomains=*

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\EnableProcessing=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true
